"""
Overkube — GitHub PR Automation Engine
=======================================
Given a service name and its recommendation, this module:

  1. Fetches the deployment manifest from a configured GitOps repo.
  2. Patches resources.requests/limits in-memory using a YAML-aware editor.
  3. Creates a feature branch, commits the patched file, and opens a PR
     with a detailed description (current vs recommended, confidence score,
     estimated monthly savings).
  4. Returns the PR URL to the caller.

Graceful-degradation:
  - If GITHUB_DRY_RUN=true  →  skips actual API calls and returns a synthetic
    diff + dry-run PR URL so the frontend can still show the result.
  - If GITHUB_TOKEN is missing  →  same dry-run fallback (never crashes).

Environment variables (all read from .env / docker env):
  GITHUB_TOKEN          Personal Access Token with `repo` scope
  GITHUB_OWNER          Repository owner (user or org)
  GITHUB_REPO           GitOps manifests repository name
  GITHUB_MANIFESTS_DIR  Path inside the repo where manifests live (default: manifests/)
  GITHUB_DRY_RUN        Set to "true" to skip real API calls (default: false)
"""

from __future__ import annotations

import logging
import re
import textwrap
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_settings():
    """Lazily import settings to avoid circular imports."""
    from app.config import settings
    return settings


def _is_dry_run() -> bool:
    import os
    return os.getenv("GITHUB_DRY_RUN", "false").lower() in ("true", "1", "yes")


def _github_client():
    """Return an authenticated PyGitHub instance, or None if unavailable."""
    try:
        from github import Github, GithubException  # type: ignore
        settings = _get_settings()
        token = settings.github_token
        if not token:
            return None, None
        g = Github(token)
        return g, GithubException
    except ImportError:
        return None, None


# ---------------------------------------------------------------------------
# PR description builder
# ---------------------------------------------------------------------------

def _build_pr_body(service_name: str, rec: dict) -> str:
    cur  = rec.get("current",     {})
    reco = rec.get("recommended", {})
    conf = rec.get("confidence",  {})
    sav  = rec.get("savings",     {})

    return textwrap.dedent(f"""
        ## ⚡ Overkube Right-Sizing Recommendation

        **Service:** `{service_name}`
        **Namespace:** `{rec.get('namespace', 'overkube')}`
        **Status:** {rec.get('status', 'unknown').replace('-', ' ').title()}

        ---

        ### Resource Changes

        | Resource | Current | Recommended | Δ |
        |----------|---------|-------------|---|
        | CPU Request | `{cur.get('cpu_request', '?')}m` | `{reco.get('cpu_request', '?')}m` | {reco.get('cpu_request', 0) - cur.get('cpu_request', 0):+d}m |
        | CPU Limit | `{cur.get('cpu_limit', '?')}m` | `{reco.get('cpu_limit', '?')}m` | {reco.get('cpu_limit', 0) - cur.get('cpu_limit', 0):+d}m |
        | Memory Request | `{cur.get('mem_request', '?')}Mi` | `{reco.get('mem_request', '?')}Mi` | {reco.get('mem_request', 0) - cur.get('mem_request', 0):+d}Mi |
        | Memory Limit | `{cur.get('mem_limit', '?')}Mi` | `{reco.get('mem_limit', '?')}Mi` | {reco.get('mem_limit', 0) - cur.get('mem_limit', 0):+d}Mi |

        ### Cost Impact

        | | Current | After |
        |-|---------|-------|
        | Monthly cost | `${cur.get('monthly_cost', 0):.2f}` | `${reco.get('monthly_cost', 0):.2f}` |
        | **Savings** | | **`${sav.get('monthly_savings', 0):.2f}/month`** |

        ### Confidence

        - **Score:** {conf.get('score', 0)}/100 — {conf.get('label', 'unknown').upper()}
        - **Samples analysed:** {rec.get('sample_count', 0):,} over {rec.get('lookback_days', 7)} days
        - **Basis:** {conf.get('reason', '')}

        ### Methodology

        Recommendations are computed from real cluster usage via:
        - **CPU request** = P90 of observed millicores usage
        - **CPU limit**   = max(P99, 1.2 × request)
        - **Memory request** = P90 of observed MiB usage
        - **Memory limit**   = P99 + 32 MiB safety buffer

        ---
        *Generated by [Overkube](https://github.com/H8rsh100/Overkube) on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*
    """).strip()


# ---------------------------------------------------------------------------
# Manifest patching
# ---------------------------------------------------------------------------

def _patch_manifest(content: str, rec: dict) -> str:
    """
    Patch resources.requests/limits in a Kubernetes YAML manifest string.
    Uses regex instead of a full YAML parser to preserve comments and formatting.
    """
    reco = rec.get("recommended", {})

    replacements = [
        # CPU request
        (r'(cpu:\s*")(\d+m)("?\s*# request)', f'cpu: "{reco.get("cpu_request")}m"  # request'),
        # Memory request
        (r'(memory:\s*")(\d+Mi)("?\s*# request)', f'memory: "{reco.get("mem_request")}Mi"  # request'),
        # CPU limit
        (r'(cpu:\s*")(\d+m)("?\s*# limit)', f'cpu: "{reco.get("cpu_limit")}m"  # limit'),
        # Memory limit
        (r'(memory:\s*")(\d+Mi)("?\s*# limit)', f'memory: "{reco.get("mem_limit")}Mi"  # limit'),
    ]

    patched = content
    for pattern, replacement in replacements:
        patched = re.sub(pattern, replacement, patched)

    return patched


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

def open_right_sizing_pr(service_name: str, rec: dict) -> dict:
    """
    Main entry-point called from the /apply endpoint.

    Returns a dict:
      {
        "pr_url":     str | None,
        "branch":     str,
        "dry_run":    bool,
        "diff":       str,       # human-readable diff summary
        "message":    str,
      }
    """
    settings = _get_settings()
    dry_run  = _is_dry_run() or not settings.github_token

    reco      = rec.get("recommended", {})
    branch    = f"overkube/rightsize-{service_name}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
    pr_body   = _build_pr_body(service_name, rec)
    pr_title  = f"chore(k8s): right-size {service_name} resources [{rec.get('status','?')}]"

    # Build a human-readable diff summary (always returned, dry-run or not)
    diff = (
        f"CPU request:  {rec.get('current',{}).get('cpu_request','?')}m → {reco.get('cpu_request','?')}m\n"
        f"CPU limit:    {rec.get('current',{}).get('cpu_limit','?')}m → {reco.get('cpu_limit','?')}m\n"
        f"Mem request:  {rec.get('current',{}).get('mem_request','?')}Mi → {reco.get('mem_request','?')}Mi\n"
        f"Mem limit:    {rec.get('current',{}).get('mem_limit','?')}Mi → {reco.get('mem_limit','?')}Mi\n"
        f"Savings:      ${rec.get('savings',{}).get('monthly_savings',0):.2f}/month"
    )

    # ── Dry-run path ──────────────────────────────────────────────────────────
    if dry_run:
        reason = "GITHUB_DRY_RUN=true" if _is_dry_run() else "GITHUB_TOKEN not configured"
        logger.info("GitHub PR dry-run for %s (%s)", service_name, reason)
        return {
            "pr_url":  None,
            "branch":  branch,
            "dry_run": True,
            "diff":    diff,
            "message": (
                f"Dry-run mode ({reason}). Would open PR '{pr_title}' "
                f"on branch '{branch}'. Set GITHUB_TOKEN + repo config to enable real PRs."
            ),
        }

    # ── Live path ─────────────────────────────────────────────────────────────
    g, GithubException = _github_client()
    if g is None:
        return {
            "pr_url":  None,
            "branch":  branch,
            "dry_run": True,
            "diff":    diff,
            "message": "PyGitHub not installed (pip install PyGithub). Falling back to dry-run.",
        }

    try:
        owner     = settings.github_owner
        repo_name = settings.github_repo
        mdir      = getattr(settings, "github_manifests_dir", "manifests")

        repo         = g.get_repo(f"{owner}/{repo_name}")
        default_ref  = repo.get_branch(repo.default_branch)
        base_sha     = default_ref.commit.sha

        # Try to find the manifest file
        manifest_path = f"{mdir}/{service_name}.yaml"
        try:
            file_obj = repo.get_contents(manifest_path)
            original = file_obj.decoded_content.decode()
            file_sha = file_obj.sha
        except GithubException:
            # File not found — create a stub
            logger.warning("Manifest %s not found in %s/%s — creating stub", manifest_path, owner, repo_name)
            original = (
                f"# Stub manifest created by Overkube for {service_name}\n"
                f"# Replace with your real manifest and re-apply.\n"
                f"apiVersion: apps/v1\nkind: Deployment\n"
                f"metadata:\n  name: {service_name}\n  namespace: overkube\n"
                f"spec:\n  template:\n    spec:\n      containers:\n        - name: app\n"
                f"          resources:\n            requests:\n"
                f"              cpu: \"{rec.get('current',{}).get('cpu_request','100')}m\"  # request\n"
                f"              memory: \"{rec.get('current',{}).get('mem_request','128')}Mi\"  # request\n"
                f"            limits:\n"
                f"              cpu: \"{rec.get('current',{}).get('cpu_limit','200')}m\"  # limit\n"
                f"              memory: \"{rec.get('current',{}).get('mem_limit','256')}Mi\"  # limit\n"
            )
            file_sha = None

        patched = _patch_manifest(original, rec)

        # Create branch
        repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base_sha)

        # Commit the patched file
        commit_msg = f"chore(k8s): right-size {service_name} via Overkube"
        if file_sha:
            repo.update_file(manifest_path, commit_msg, patched, file_sha, branch=branch)
        else:
            repo.create_file(manifest_path, commit_msg, patched, branch=branch)

        # Open the PR
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch,
            base=repo.default_branch,
        )

        logger.info("PR opened: %s", pr.html_url)
        return {
            "pr_url":  pr.html_url,
            "branch":  branch,
            "dry_run": False,
            "diff":    diff,
            "message": f"Pull request opened: {pr.html_url}",
        }

    except Exception as exc:
        logger.exception("GitHub PR failed for %s", service_name)
        return {
            "pr_url":  None,
            "branch":  branch,
            "dry_run": True,
            "diff":    diff,
            "message": f"GitHub API error: {exc}. Falling back to dry-run.",
        }
